// <auto-generated />
using System;
using System.Collections.Generic;
using MediaAssetManager.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MediaAssetManager.Infrastructure.Migrations
{
    [DbContext(typeof(MediaAssetContext))]
    [Migration("20260211184214_AddViewCountTrigger")]
    partial class AddViewCountTrigger
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MediaAssetManager.Core.Entities.AssetView", b =>
                {
                    b.Property<long>("ViewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("view_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ViewId"));

                    b.Property<int>("AssetId")
                        .HasColumnType("integer")
                        .HasColumnName("asset_id");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("ViewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("viewed_at");

                    b.HasKey("ViewId")
                        .HasName("pk_asset_views");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asset_views_user_id");

                    b.HasIndex("ViewedAt")
                        .HasDatabaseName("ix_asset_views_viewed_at");

                    b.HasIndex("AssetId", "ViewedAt")
                        .HasDatabaseName("ix_asset_views_asset_id_viewed_at");

                    b.ToTable("asset_views", (string)null);
                });

            modelBuilder.Entity("MediaAssetManager.Core.Entities.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClientId"));

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("client_name");

                    b.Property<string>("ClientPublicId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("client_public_id");

                    b.Property<string>("ClientSecretHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("client_secret_hash");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.HasKey("ClientId")
                        .HasName("pk_clients");

                    b.HasIndex("ClientPublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_clients_client_public_id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_clients_is_active");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("MediaAssetManager.Core.Entities.Favorite", b =>
                {
                    b.Property<int>("FavoriteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("favorite_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FavoriteId"));

                    b.Property<int>("AssetId")
                        .HasColumnType("integer")
                        .HasColumnName("asset_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("FavoriteId")
                        .HasName("pk_favorites");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("ix_favorites_asset_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_favorites_created_at");

                    b.HasIndex("UserId", "AssetId")
                        .IsUnique()
                        .HasDatabaseName("ix_favorites_user_id_asset_id");

                    b.ToTable("favorites", (string)null);
                });

            modelBuilder.Entity("MediaAssetManager.Core.Entities.MediaAsset", b =>
                {
                    b.Property<int>("AssetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("asset_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AssetId"));

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<string>("GameTitle")
                        .HasColumnType("text")
                        .HasColumnName("game_title");

                    b.Property<bool>("IsCompressed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_compressed");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<DateTime?>("LastViewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_viewed_at");

                    b.Property<int>("Lifecycle")
                        .HasColumnType("integer")
                        .HasColumnName("lifecycle");

                    b.Property<int>("MediaType")
                        .HasColumnType("integer")
                        .HasColumnName("media_type");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("original_file_name");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("ProcessingError")
                        .HasColumnType("text")
                        .HasColumnName("processing_error");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_path");

                    b.Property<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("tags");

                    b.Property<string>("ThumbnailPath")
                        .HasColumnType("text")
                        .HasColumnName("thumbnail_path");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("ViewCount")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("view_count");

                    b.HasKey("AssetId")
                        .HasName("pk_media_assets");

                    b.HasIndex("ContentHash")
                        .IsUnique()
                        .HasDatabaseName("ix_media_assets_content_hash");

                    b.HasIndex("GameTitle")
                        .HasDatabaseName("ix_media_assets_game_title");

                    b.HasIndex("MediaType")
                        .HasDatabaseName("ix_media_assets_media_type");

                    b.HasIndex("UploadedAt")
                        .HasDatabaseName("ix_media_assets_uploaded_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_media_assets_user_id");

                    b.HasIndex("IsPublic", "UserId")
                        .HasDatabaseName("ix_media_assets_is_public_user_id");

                    b.ToTable("media_assets", (string)null);
                });

            modelBuilder.Entity("MediaAssetManager.Core.Entities.Playlist", b =>
                {
                    b.Property<int>("PlaylistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("playlist_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PlaylistId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("PlaylistId")
                        .HasName("pk_playlists");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_playlists_user_id");

                    b.HasIndex("UserId", "IsPublic")
                        .HasDatabaseName("ix_playlists_user_id_is_public");

                    b.ToTable("playlists", (string)null);
                });

            modelBuilder.Entity("MediaAssetManager.Core.Entities.PlaylistItem", b =>
                {
                    b.Property<int>("PlaylistItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("playlist_item_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PlaylistItemId"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<int>("AssetId")
                        .HasColumnType("integer")
                        .HasColumnName("asset_id");

                    b.Property<int>("PlaylistId")
                        .HasColumnType("integer")
                        .HasColumnName("playlist_id");

                    b.HasKey("PlaylistItemId")
                        .HasName("pk_playlist_items");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("ix_playlist_items_asset_id");

                    b.HasIndex("PlaylistId", "AssetId")
                        .IsUnique()
                        .HasDatabaseName("ix_playlist_items_playlist_id_asset_id");

                    b.ToTable("playlist_items", (string)null);
                });

            modelBuilder.Entity("MediaAssetManager.Core.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("UserId")
                        .HasName("pk_users");

                    b.HasIndex("Username")
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("MediaAssetManager.Core.Entities.VideoMetadata", b =>
                {
                    b.Property<int>("VideoMetadataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("video_metadata_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VideoMetadataId"));

                    b.Property<int>("AssetId")
                        .HasColumnType("integer")
                        .HasColumnName("asset_id");

                    b.Property<string>("AudioCodec")
                        .HasColumnType("text")
                        .HasColumnName("audio_codec");

                    b.Property<int?>("BitrateKbps")
                        .HasColumnType("integer")
                        .HasColumnName("bitrate_kbps");

                    b.Property<string>("Codec")
                        .HasColumnType("text")
                        .HasColumnName("codec");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_seconds");

                    b.Property<decimal>("FrameRate")
                        .HasColumnType("numeric")
                        .HasColumnName("frame_rate");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<int>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("VideoMetadataId")
                        .HasName("pk_video_metadata");

                    b.HasIndex("AssetId")
                        .IsUnique()
                        .HasDatabaseName("ix_video_metadata_asset_id");

                    b.HasIndex("Width", "Height")
                        .HasDatabaseName("ix_video_metadata_width_height");

                    b.ToTable("video_metadata", (string)null);
                });

            modelBuilder.Entity("MediaAssetManager.Core.Entities.AssetView", b =>
                {
                    b.HasOne("MediaAssetManager.Core.Entities.MediaAsset", "Asset")
                        .WithMany("Views")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asset_views_media_assets_asset_id");

                    b.HasOne("MediaAssetManager.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_asset_views_users_user_id");

                    b.Navigation("Asset");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MediaAssetManager.Core.Entities.Favorite", b =>
                {
                    b.HasOne("MediaAssetManager.Core.Entities.MediaAsset", "Asset")
                        .WithMany("Favorites")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_favorites_media_assets_asset_id");

                    b.HasOne("MediaAssetManager.Core.Entities.User", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_favorites_users_user_id");

                    b.Navigation("Asset");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MediaAssetManager.Core.Entities.MediaAsset", b =>
                {
                    b.HasOne("MediaAssetManager.Core.Entities.User", "User")
                        .WithMany("Assets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_media_assets_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MediaAssetManager.Core.Entities.Playlist", b =>
                {
                    b.HasOne("MediaAssetManager.Core.Entities.User", "User")
                        .WithMany("Playlists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_playlists_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MediaAssetManager.Core.Entities.PlaylistItem", b =>
                {
                    b.HasOne("MediaAssetManager.Core.Entities.MediaAsset", "Asset")
                        .WithMany("PlaylistItems")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_playlist_items_media_assets_asset_id");

                    b.HasOne("MediaAssetManager.Core.Entities.Playlist", "Playlist")
                        .WithMany("Items")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_playlist_items_playlists_playlist_id");

                    b.Navigation("Asset");

                    b.Navigation("Playlist");
                });

            modelBuilder.Entity("MediaAssetManager.Core.Entities.VideoMetadata", b =>
                {
                    b.HasOne("MediaAssetManager.Core.Entities.MediaAsset", "Asset")
                        .WithOne("VideoMetadata")
                        .HasForeignKey("MediaAssetManager.Core.Entities.VideoMetadata", "AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_video_metadata_media_assets_asset_id");

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("MediaAssetManager.Core.Entities.MediaAsset", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("PlaylistItems");

                    b.Navigation("VideoMetadata");

                    b.Navigation("Views");
                });

            modelBuilder.Entity("MediaAssetManager.Core.Entities.Playlist", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("MediaAssetManager.Core.Entities.User", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("Favorites");

                    b.Navigation("Playlists");
                });
#pragma warning restore 612, 618
        }
    }
}
